openapi: 3.0.0
info:
  title: Film Streaming API
  description: Egy RESTful API a film streaming adatok kezelésére.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /filmek:
    get:
      summary: Az összes film lekérése
      responses:
        '200':
          description: A filmek listája
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Film'
    post:
      summary: Új film létrehozása
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        '201':
          description: Film létrehozva
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
  /filmek/{id}:
    get:
      summary: Film lekérése ID alapján
      parameters:
        - name: id
          in: path
          required: true
          description: A film azonosítója
          schema:
            type: string
      responses:
        '200':
          description: Egy film objektum
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        '404':
          description: Film nem található
    put:
      summary: Film frissítése ID alapján
      parameters:
        - name: id
          in: path
          required: true
          description: A film azonosítója
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        '200':
          description: Film frissítve
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        '404':
          description: Film nem található
    delete:
      summary: Film törlése ID alapján
      parameters:
        - name: id
          in: path
          required: true
          description: A film azonosítója
          schema:
            type: string
      responses:
        '204':
          description: Film törölve
        '404':
          description: Film nem található
  /sajatlista:
    get:
      summary: Az összes film lekérése
      responses:
        '200':
          description: A filmek listája
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Film'
    post:
      summary: Új film létrehozása
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        '201':
          description: Film létrehozva
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
  /sajatlista/{id}:
    get:
      summary: Film lekérése ID alapján
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Egy film
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        '404':
          description: Film nem található
    put:
      summary: Film frissítése ID alapján
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
      responses:
        '200':
          description: Film frissítve
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        '404':
          description: Film nem található
    delete:
      summary: Film törlése ID alapján
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Film törölve
        '404':
          description: Film nem található
components:
  schemas:
    Film:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        genre:
          type: string
        duration:
          type: integer
        releaseDate:
          type: string
          format: date
        streamingDate:
          type: string
          format: date
        type:
          type: string
          enum:
            - Film
            - Sorozat
        imageUrl:
          type: string
          format: uri